### ISSUE TITLE
how to choose another port?

### ISSUE THREAD

**Issue by ghost** [leots/Arduino-PC-Monitor#6]
Hello. Please tell me how to choose another port? I have Arduino connected to port 17 (port number 1 is occupied by another device).

**Comment by leots** [comment]
Hi,

Since you know what port you want to connect to, you can try replacing the main function with this modified one: https://pastebin.com/2Vyfxzif

I removed the automatic port check, so you need to set the port you want to use in line 7 (of the pastebin). On my system ports are named "COM[number]" so I put COM17.

Tell me if it worked :)

Thanks

**Comment by ghost** [comment]
Thanks, the code has changed, but now it gives out other errors. About errors I wrote here: [https://github.com/leots/Arduino-PC-Monitor/issues/5](https://github.com/leots/Arduino-PC-Monitor/issues/5)

**Comment by forfrends** [comment]
https://github.com/leots/Arduino-PC-Monitor/issues/5
